server:
  port: 8083

spring:
  application:
    name: job-service
    description: Job Service
  datasource:
    url: jdbc:postgresql://localhost:5432/job-portal-db
    username: postgres
    password: postgresPassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false