server:
  port: 8081

spring:
  application:
    name: user-service
    description: user-service - auth, profile, and user management
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service
    username: postgres
    password: postgresPassword
    driver-class-name: org.postgresql.Driver

